// Generated by scripts/vendor-flags.mjs from mledoze/countries
// (https://github.com/mledoze/countries, ODbL 1.0). Do not edit by hand.
//
// Every seed picks flags by their place in this list, so its order is part
// of every game ever played. See the script before regenerating it.

export const COUNTRIES = [
 {
  "code": "AD",
  "name": "Andorra",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "Principality of Andorra",
   "Principat d'Andorra"
  ]
 },
 {
  "code": "AE",
  "name": "United Arab Emirates",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "UAE",
   "Emirates"
  ]
 },
 {
  "code": "AF",
  "name": "Afghanistan",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "Islamic Republic of Afghanistan",
   "Afġānistān"
  ]
 },
 {
  "code": "AG",
  "name": "Antigua and Barbuda",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": []
 },
 {
  "code": "AL",
  "name": "Albania",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "Republic of Albania",
   "Shqipëri",
   "Shqipëria",
   "Shqipnia"
  ]
 },
 {
  "code": "AM",
  "name": "Armenia",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Republic of Armenia",
   "Hayastan",
   "Հայաստանի Հանրապետություն"
  ]
 },
 {
  "code": "AO",
  "name": "Angola",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "Republic of Angola",
   "República de Angola",
   "ʁɛpublika de an'ɡɔla"
  ]
 },
 {
  "code": "AR",
  "name": "Argentina",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Argentine Republic",
   "República Argentina"
  ]
 },
 {
  "code": "AT",
  "name": "Austria",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "Republic of Austria",
   "Osterreich",
   "Oesterreich"
  ]
 },
 {
  "code": "AU",
  "name": "Australia",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "aliases": [
   "Commonwealth of Australia"
  ]
 },
 {
  "code": "AZ",
  "name": "Azerbaijan",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Republic of Azerbaijan",
   "Azərbaycan Respublikası"
  ]
 },
 {
  "code": "BA",
  "name": "Bosnia and Herzegovina",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "Bosnia-Herzegovina",
   "Босна и Херцеговина"
  ]
 },
 {
  "code": "BB",
  "name": "Barbados",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": []
 },
 {
  "code": "BD",
  "name": "Bangladesh",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "People's Republic of Bangladesh",
   "Gônôprôjatôntri Bangladesh"
  ]
 },
 {
  "code": "BE",
  "name": "Belgium",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "Kingdom of Belgium",
   "België",
   "Belgie",
   "Belgien",
   "Belgique",
   "Koninkrijk België",
   "Royaume de Belgique",
   "Königreich Belgien"
  ]
 },
 {
  "code": "BF",
  "name": "Burkina Faso",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": []
 },
 {
  "code": "BG",
  "name": "Bulgaria",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "Republic of Bulgaria",
   "Република България"
  ]
 },
 {
  "code": "BH",
  "name": "Bahrain",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Kingdom of Bahrain",
   "Mamlakat al-Baḥrayn"
  ]
 },
 {
  "code": "BI",
  "name": "Burundi",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Burundi",
   "Republika y'Uburundi",
   "République du Burundi"
  ]
 },
 {
  "code": "BJ",
  "name": "Benin",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Benin",
   "République du Bénin"
  ]
 },
 {
  "code": "BN",
  "name": "Brunei",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Nation of Brunei, Abode of Peace",
   "Brunei Darussalam",
   "Nation of Brunei",
   "the Abode of Peace"
  ]
 },
 {
  "code": "BO",
  "name": "Bolivia",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Plurinational State of Bolivia",
   "Buliwya",
   "Wuliwya",
   "Bolivia, Plurinational State of",
   "Estado Plurinacional de Bolivia",
   "Buliwya Mamallaqta",
   "Wuliwya Suyu",
   "Tetã Volívia"
  ]
 },
 {
  "code": "BR",
  "name": "Brazil",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Federative Republic of Brazil",
   "Brasil",
   "República Federativa do Brasil"
  ]
 },
 {
  "code": "BS",
  "name": "Bahamas",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "Commonwealth of the Bahamas"
  ]
 },
 {
  "code": "BT",
  "name": "Bhutan",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "Kingdom of Bhutan"
  ]
 },
 {
  "code": "BW",
  "name": "Botswana",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "Republic of Botswana",
   "Lefatshe la Botswana"
  ]
 },
 {
  "code": "BY",
  "name": "Belarus",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "aliases": [
   "Republic of Belarus",
   "Bielaruś",
   "Белоруссия",
   "Республика Белоруссия"
  ]
 },
 {
  "code": "BZ",
  "name": "Belize",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": []
 },
 {
  "code": "CA",
  "name": "Canada",
  "region": "Americas",
  "subregion": "North America",
  "aliases": []
 },
 {
  "code": "CD",
  "name": "DR Congo",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "Democratic Republic of the Congo",
   "Congo-Kinshasa",
   "Congo, the Democratic Republic of the",
   "Democratic Republic of Congo",
   "DRC"
  ]
 },
 {
  "code": "CF",
  "name": "Central African Republic",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "République centrafricaine"
  ]
 },
 {
  "code": "CG",
  "name": "Congo",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "Republic of the Congo",
   "Congo-Brazzaville"
  ]
 },
 {
  "code": "CH",
  "name": "Switzerland",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "Swiss Confederation",
   "Schweiz",
   "Suisse",
   "Svizzera",
   "Svizra"
  ]
 },
 {
  "code": "CI",
  "name": "Ivory Coast",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Côte d'Ivoire",
   "Côte d'Ivoire",
   "Cote d'Ivoire",
   "République de Côte d'Ivoire"
  ]
 },
 {
  "code": "CL",
  "name": "Chile",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Republic of Chile",
   "República de Chile"
  ]
 },
 {
  "code": "CM",
  "name": "Cameroon",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "Republic of Cameroon",
   "République du Cameroun"
  ]
 },
 {
  "code": "CN",
  "name": "China",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": [
   "People's Republic of China",
   "Zhōngguó",
   "Zhongguo",
   "Zhonghua",
   "中华人民共和国",
   "Zhōnghuá Rénmín Gònghéguó"
  ]
 },
 {
  "code": "CO",
  "name": "Colombia",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Republic of Colombia",
   "República de Colombia"
  ]
 },
 {
  "code": "CR",
  "name": "Costa Rica",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "Republic of Costa Rica",
   "República de Costa Rica"
  ]
 },
 {
  "code": "CU",
  "name": "Cuba",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "Republic of Cuba",
   "República de Cuba"
  ]
 },
 {
  "code": "CV",
  "name": "Cape Verde",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Cabo Verde",
   "República de Cabo Verde"
  ]
 },
 {
  "code": "CY",
  "name": "Cyprus",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "Republic of Cyprus",
   "Kýpros",
   "Kıbrıs",
   "Κυπριακή Δημοκρατία",
   "Kıbrıs Cumhuriyeti"
  ]
 },
 {
  "code": "CZ",
  "name": "Czechia",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "Czech Republic",
   "Česká republika",
   "Česko"
  ]
 },
 {
  "code": "DE",
  "name": "Germany",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "Federal Republic of Germany",
   "Bundesrepublik Deutschland"
  ]
 },
 {
  "code": "DJ",
  "name": "Djibouti",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Djibouti",
   "Jabuuti",
   "Gabuuti",
   "République de Djibouti",
   "Gabuutih Ummuuno",
   "Jamhuuriyadda Jabuuti"
  ]
 },
 {
  "code": "DK",
  "name": "Denmark",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "Kingdom of Denmark",
   "Danmark",
   "Kongeriget Danmark"
  ]
 },
 {
  "code": "DM",
  "name": "Dominica",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "Commonwealth of Dominica",
   "Dominique",
   "Wai‘tu kubuli"
  ]
 },
 {
  "code": "DO",
  "name": "Dominican Republic",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": []
 },
 {
  "code": "DZ",
  "name": "Algeria",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "People's Democratic Republic of Algeria",
   "Dzayer",
   "Algérie"
  ]
 },
 {
  "code": "EC",
  "name": "Ecuador",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Republic of Ecuador",
   "República del Ecuador"
  ]
 },
 {
  "code": "EE",
  "name": "Estonia",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "Republic of Estonia",
   "Eesti",
   "Eesti Vabariik"
  ]
 },
 {
  "code": "EG",
  "name": "Egypt",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "Arab Republic of Egypt"
  ]
 },
 {
  "code": "ER",
  "name": "Eritrea",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "State of Eritrea",
   "ሃገረ ኤርትራ",
   "Dawlat Iritriyá",
   "ʾErtrā",
   "Iritriyā"
  ]
 },
 {
  "code": "ES",
  "name": "Spain",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "Kingdom of Spain",
   "Reino de España"
  ]
 },
 {
  "code": "ET",
  "name": "Ethiopia",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Federal Democratic Republic of Ethiopia",
   "ʾĪtyōṗṗyā",
   "የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ"
  ]
 },
 {
  "code": "FI",
  "name": "Finland",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "Republic of Finland",
   "Suomi",
   "Suomen tasavalta",
   "Republiken Finland"
  ]
 },
 {
  "code": "FJ",
  "name": "Fiji",
  "region": "Oceania",
  "subregion": "Melanesia",
  "aliases": [
   "Republic of Fiji",
   "Viti",
   "Matanitu ko Viti",
   "Fijī Gaṇarājya"
  ]
 },
 {
  "code": "FM",
  "name": "Micronesia",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "Federated States of Micronesia",
   "Micronesia, Federated States of"
  ]
 },
 {
  "code": "FR",
  "name": "France",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "French Republic",
   "République française"
  ]
 },
 {
  "code": "GA",
  "name": "Gabon",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "Gabonese Republic",
   "République Gabonaise"
  ]
 },
 {
  "code": "GB",
  "name": "United Kingdom",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "United Kingdom of Great Britain and Northern Ireland",
   "UK",
   "Great Britain"
  ]
 },
 {
  "code": "GD",
  "name": "Grenada",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": []
 },
 {
  "code": "GE",
  "name": "Georgia",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Sakartvelo"
  ]
 },
 {
  "code": "GH",
  "name": "Ghana",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Ghana"
  ]
 },
 {
  "code": "GM",
  "name": "Gambia",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of the Gambia"
  ]
 },
 {
  "code": "GN",
  "name": "Guinea",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Guinea",
   "République de Guinée"
  ]
 },
 {
  "code": "GQ",
  "name": "Equatorial Guinea",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "Republic of Equatorial Guinea",
   "República de Guinea Ecuatorial",
   "République de Guinée équatoriale",
   "República da Guiné Equatorial"
  ]
 },
 {
  "code": "GR",
  "name": "Greece",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "Hellenic Republic",
   "Elláda",
   "Ελληνική Δημοκρατία"
  ]
 },
 {
  "code": "GT",
  "name": "Guatemala",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "Republic of Guatemala"
  ]
 },
 {
  "code": "GW",
  "name": "Guinea-Bissau",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Guinea-Bissau",
   "República da Guiné-Bissau"
  ]
 },
 {
  "code": "GY",
  "name": "Guyana",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Co-operative Republic of Guyana"
  ]
 },
 {
  "code": "HN",
  "name": "Honduras",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "Republic of Honduras",
   "República de Honduras"
  ]
 },
 {
  "code": "HR",
  "name": "Croatia",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "Republic of Croatia",
   "Hrvatska",
   "Republika Hrvatska"
  ]
 },
 {
  "code": "HT",
  "name": "Haiti",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "Republic of Haiti",
   "République d'Haïti",
   "Repiblik Ayiti"
  ]
 },
 {
  "code": "HU",
  "name": "Hungary",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": []
 },
 {
  "code": "ID",
  "name": "Indonesia",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Republic of Indonesia",
   "Republik Indonesia"
  ]
 },
 {
  "code": "IE",
  "name": "Ireland",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "Republic of Ireland",
   "Éire",
   "Poblacht na hÉireann"
  ]
 },
 {
  "code": "IL",
  "name": "Israel",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "State of Israel",
   "Medīnat Yisrā'el"
  ]
 },
 {
  "code": "IN",
  "name": "India",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "Republic of India",
   "Bhārat",
   "Bharat Ganrajya",
   "இந்தியா"
  ]
 },
 {
  "code": "IQ",
  "name": "Iraq",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Republic of Iraq",
   "Jumhūriyyat al-‘Irāq"
  ]
 },
 {
  "code": "IR",
  "name": "Iran",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "Islamic Republic of Iran",
   "Iran, Islamic Republic of",
   "Jomhuri-ye Eslāmi-ye Irān"
  ]
 },
 {
  "code": "IS",
  "name": "Iceland",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "Island",
   "Republic of Iceland",
   "Lýðveldið Ísland"
  ]
 },
 {
  "code": "IT",
  "name": "Italy",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "Italian Republic",
   "Repubblica italiana"
  ]
 },
 {
  "code": "JM",
  "name": "Jamaica",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": []
 },
 {
  "code": "JO",
  "name": "Jordan",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Hashemite Kingdom of Jordan",
   "al-Mamlakah al-Urdunīyah al-Hāshimīyah"
  ]
 },
 {
  "code": "JP",
  "name": "Japan",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": [
   "Nippon",
   "Nihon"
  ]
 },
 {
  "code": "KE",
  "name": "Kenya",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Kenya",
   "Jamhuri ya Kenya"
  ]
 },
 {
  "code": "KG",
  "name": "Kyrgyzstan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": [
   "Kyrgyz Republic",
   "Киргизия",
   "Кыргыз Республикасы",
   "Kyrgyz Respublikasy"
  ]
 },
 {
  "code": "KH",
  "name": "Cambodia",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Kingdom of Cambodia"
  ]
 },
 {
  "code": "KI",
  "name": "Kiribati",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "Independent and Sovereign Republic of Kiribati",
   "Republic of Kiribati",
   "Ribaberiki Kiribati"
  ]
 },
 {
  "code": "KM",
  "name": "Comoros",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Union of the Comoros",
   "Union des Comores",
   "Udzima wa Komori",
   "al-Ittiḥād al-Qumurī"
  ]
 },
 {
  "code": "KN",
  "name": "Saint Kitts and Nevis",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "Federation of Saint Christopher and Nevis"
  ]
 },
 {
  "code": "KP",
  "name": "North Korea",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": [
   "Democratic People's Republic of Korea",
   "DPRK",
   "조선민주주의인민공화국",
   "Chosŏn Minjujuŭi Inmin Konghwaguk",
   "Korea, Democratic People's Republic of",
   "북한",
   "북조선"
  ]
 },
 {
  "code": "KR",
  "name": "South Korea",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": [
   "Republic of Korea",
   "Korea, Republic of",
   "남한",
   "남조선"
  ]
 },
 {
  "code": "KW",
  "name": "Kuwait",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "State of Kuwait",
   "Dawlat al-Kuwait"
  ]
 },
 {
  "code": "KZ",
  "name": "Kazakhstan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": [
   "Republic of Kazakhstan",
   "Qazaqstan",
   "Казахстан",
   "Қазақстан Республикасы",
   "Qazaqstan Respublïkası",
   "Республика Казахстан",
   "Respublika Kazakhstan"
  ]
 },
 {
  "code": "LA",
  "name": "Laos",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Lao People's Democratic Republic",
   "Lao",
   "Sathalanalat Paxathipatai Paxaxon Lao"
  ]
 },
 {
  "code": "LB",
  "name": "Lebanon",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Lebanese Republic",
   "Al-Jumhūrīyah Al-Libnānīyah"
  ]
 },
 {
  "code": "LC",
  "name": "Saint Lucia",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": []
 },
 {
  "code": "LI",
  "name": "Liechtenstein",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "Principality of Liechtenstein",
   "Fürstentum Liechtenstein"
  ]
 },
 {
  "code": "LK",
  "name": "Sri Lanka",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "Democratic Socialist Republic of Sri Lanka",
   "ilaṅkai"
  ]
 },
 {
  "code": "LR",
  "name": "Liberia",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Liberia"
  ]
 },
 {
  "code": "LS",
  "name": "Lesotho",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "Kingdom of Lesotho",
   "Muso oa Lesotho"
  ]
 },
 {
  "code": "LT",
  "name": "Lithuania",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "Republic of Lithuania",
   "Lietuvos Respublika"
  ]
 },
 {
  "code": "LU",
  "name": "Luxembourg",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "Grand Duchy of Luxembourg",
   "Grand-Duché de Luxembourg",
   "Großherzogtum Luxemburg",
   "Groussherzogtum Lëtzebuerg"
  ]
 },
 {
  "code": "LV",
  "name": "Latvia",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "Republic of Latvia",
   "Latvijas Republika"
  ]
 },
 {
  "code": "LY",
  "name": "Libya",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "State of Libya",
   "Dawlat Libya"
  ]
 },
 {
  "code": "MA",
  "name": "Morocco",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "Kingdom of Morocco",
   "Al-Mamlakah al-Maġribiyah"
  ]
 },
 {
  "code": "MC",
  "name": "Monaco",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "Principality of Monaco",
   "Principauté de Monaco"
  ]
 },
 {
  "code": "MD",
  "name": "Moldova",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "aliases": [
   "Republic of Moldova",
   "Moldova, Republic of",
   "Republica Moldova"
  ]
 },
 {
  "code": "ME",
  "name": "Montenegro",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "Crna Gora"
  ]
 },
 {
  "code": "MG",
  "name": "Madagascar",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Madagascar",
   "Repoblikan'i Madagasikara",
   "République de Madagascar"
  ]
 },
 {
  "code": "MH",
  "name": "Marshall Islands",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "Republic of the Marshall Islands",
   "Aolepān Aorōkin M̧ajeļ"
  ]
 },
 {
  "code": "MK",
  "name": "North Macedonia",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "Republic of North Macedonia",
   "The former Yugoslav Republic of Macedonia",
   "Macedonia, The Former Yugoslav Republic of",
   "Република Северна Македонија",
   "Macedonia"
  ]
 },
 {
  "code": "ML",
  "name": "Mali",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Mali",
   "République du Mali"
  ]
 },
 {
  "code": "MM",
  "name": "Myanmar",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Republic of the Union of Myanmar",
   "Burma",
   "Pyidaunzu Thanmăda Myăma Nainngandaw"
  ]
 },
 {
  "code": "MN",
  "name": "Mongolia",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": []
 },
 {
  "code": "MR",
  "name": "Mauritania",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Islamic Republic of Mauritania",
   "al-Jumhūriyyah al-ʾIslāmiyyah al-Mūrītāniyyah"
  ]
 },
 {
  "code": "MT",
  "name": "Malta",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "Republic of Malta",
   "Repubblika ta' Malta"
  ]
 },
 {
  "code": "MU",
  "name": "Mauritius",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Mauritius",
   "République de Maurice"
  ]
 },
 {
  "code": "MV",
  "name": "Maldives",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "Republic of the Maldives",
   "Maldive Islands",
   "Dhivehi Raajjeyge Jumhooriyya"
  ]
 },
 {
  "code": "MW",
  "name": "Malawi",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Malawi"
  ]
 },
 {
  "code": "MX",
  "name": "Mexico",
  "region": "Americas",
  "subregion": "North America",
  "aliases": [
   "United Mexican States",
   "Mexicanos",
   "Estados Unidos Mexicanos"
  ]
 },
 {
  "code": "MY",
  "name": "Malaysia",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": []
 },
 {
  "code": "MZ",
  "name": "Mozambique",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Mozambique",
   "República de Moçambique"
  ]
 },
 {
  "code": "NA",
  "name": "Namibia",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "Republic of Namibia",
   "Namibië"
  ]
 },
 {
  "code": "NE",
  "name": "Niger",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Niger",
   "Nijar"
  ]
 },
 {
  "code": "NG",
  "name": "Nigeria",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Federal Republic of Nigeria",
   "Nijeriya",
   "Naíjíríà"
  ]
 },
 {
  "code": "NI",
  "name": "Nicaragua",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "Republic of Nicaragua",
   "República de Nicaragua"
  ]
 },
 {
  "code": "NL",
  "name": "Netherlands",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "Kingdom of the Netherlands",
   "Holland",
   "Nederland",
   "The Netherlands"
  ]
 },
 {
  "code": "NO",
  "name": "Norway",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "Kingdom of Norway",
   "Norge",
   "Noreg",
   "Kongeriket Norge",
   "Kongeriket Noreg"
  ]
 },
 {
  "code": "NP",
  "name": "Nepal",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "Federal Democratic Republic of Nepal",
   "Loktāntrik Ganatantra Nepāl"
  ]
 },
 {
  "code": "NR",
  "name": "Nauru",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "Republic of Nauru",
   "Naoero",
   "Pleasant Island",
   "Ripublik Naoero"
  ]
 },
 {
  "code": "NZ",
  "name": "New Zealand",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "aliases": [
   "Aotearoa"
  ]
 },
 {
  "code": "OM",
  "name": "Oman",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Sultanate of Oman",
   "Salṭanat ʻUmān"
  ]
 },
 {
  "code": "PA",
  "name": "Panama",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "Republic of Panama",
   "República de Panamá"
  ]
 },
 {
  "code": "PE",
  "name": "Peru",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Republic of Peru",
   "República del Perú"
  ]
 },
 {
  "code": "PG",
  "name": "Papua New Guinea",
  "region": "Oceania",
  "subregion": "Melanesia",
  "aliases": [
   "Independent State of Papua New Guinea",
   "Independen Stet bilong Papua Niugini"
  ]
 },
 {
  "code": "PH",
  "name": "Philippines",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Republic of the Philippines",
   "Repúblika ng Pilipinas"
  ]
 },
 {
  "code": "PK",
  "name": "Pakistan",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "Islamic Republic of Pakistan",
   "Pākistān",
   "Islāmī Jumhūriya'eh Pākistān"
  ]
 },
 {
  "code": "PL",
  "name": "Poland",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "Republic of Poland",
   "Rzeczpospolita Polska"
  ]
 },
 {
  "code": "PT",
  "name": "Portugal",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "Portuguese Republic",
   "Portuguesa",
   "República Portuguesa"
  ]
 },
 {
  "code": "PW",
  "name": "Palau",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "Republic of Palau",
   "Beluu er a Belau"
  ]
 },
 {
  "code": "PY",
  "name": "Paraguay",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Republic of Paraguay",
   "República del Paraguay",
   "Tetã Paraguái"
  ]
 },
 {
  "code": "QA",
  "name": "Qatar",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "State of Qatar",
   "Dawlat Qaṭar"
  ]
 },
 {
  "code": "RO",
  "name": "Romania",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "Rumania",
   "Roumania",
   "România"
  ]
 },
 {
  "code": "RS",
  "name": "Serbia",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "Republic of Serbia",
   "Srbija",
   "Republika Srbija",
   "Србија",
   "Република Србија"
  ]
 },
 {
  "code": "RU",
  "name": "Russia",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "aliases": [
   "Russian Federation",
   "Российская Федерация"
  ]
 },
 {
  "code": "RW",
  "name": "Rwanda",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Rwanda",
   "Repubulika y'u Rwanda",
   "République du Rwanda"
  ]
 },
 {
  "code": "SA",
  "name": "Saudi Arabia",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Kingdom of Saudi Arabia",
   "Saudi",
   "Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah"
  ]
 },
 {
  "code": "SB",
  "name": "Solomon Islands",
  "region": "Oceania",
  "subregion": "Melanesia",
  "aliases": []
 },
 {
  "code": "SC",
  "name": "Seychelles",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Seychelles",
   "Repiblik Sesel",
   "République des Seychelles"
  ]
 },
 {
  "code": "SD",
  "name": "Sudan",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "Republic of the Sudan",
   "Jumhūrīyat as-Sūdān"
  ]
 },
 {
  "code": "SE",
  "name": "Sweden",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "Kingdom of Sweden",
   "Konungariket Sverige"
  ]
 },
 {
  "code": "SG",
  "name": "Singapore",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Republic of Singapore",
   "Singapura",
   "Republik Singapura",
   "新加坡共和国"
  ]
 },
 {
  "code": "SI",
  "name": "Slovenia",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "Republic of Slovenia",
   "Republika Slovenija"
  ]
 },
 {
  "code": "SK",
  "name": "Slovakia",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "Slovak Republic",
   "Slovenská republika"
  ]
 },
 {
  "code": "SL",
  "name": "Sierra Leone",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Sierra Leone"
  ]
 },
 {
  "code": "SM",
  "name": "San Marino",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "Most Serene Republic of San Marino",
   "Republic of San Marino",
   "Repubblica di San Marino"
  ]
 },
 {
  "code": "SN",
  "name": "Senegal",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Republic of Senegal",
   "République du Sénégal"
  ]
 },
 {
  "code": "SO",
  "name": "Somalia",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Federal Republic of Somalia",
   "aṣ-Ṣūmāl",
   "Jamhuuriyadda Federaalka Soomaaliya",
   "Jumhūriyyat aṣ-Ṣūmāl al-Fiderāliyya"
  ]
 },
 {
  "code": "SR",
  "name": "Suriname",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Republic of Suriname",
   "Sarnam",
   "Sranangron",
   "Republiek Suriname"
  ]
 },
 {
  "code": "SS",
  "name": "South Sudan",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "Republic of South Sudan"
  ]
 },
 {
  "code": "ST",
  "name": "São Tomé and Príncipe",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "Democratic Republic of São Tomé and Príncipe",
   "Sao Tome and Principe",
   "República Democrática de São Tomé e Príncipe"
  ]
 },
 {
  "code": "SV",
  "name": "El Salvador",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "Republic of El Salvador",
   "República de El Salvador"
  ]
 },
 {
  "code": "SY",
  "name": "Syria",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Syrian Arab Republic",
   "Al-Jumhūrīyah Al-ʻArabīyah As-Sūrīyah"
  ]
 },
 {
  "code": "SZ",
  "name": "Eswatini",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "Kingdom of Eswatini",
   "Swaziland",
   "weSwatini",
   "Swatini",
   "Ngwane",
   "Umbuso weSwatini"
  ]
 },
 {
  "code": "TD",
  "name": "Chad",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "Republic of Chad",
   "Tchad",
   "République du Tchad"
  ]
 },
 {
  "code": "TG",
  "name": "Togo",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "Togolese Republic",
   "Togolese",
   "République Togolaise"
  ]
 },
 {
  "code": "TH",
  "name": "Thailand",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Kingdom of Thailand",
   "Prathet",
   "Thai",
   "ราชอาณาจักรไทย",
   "Ratcha Anachak Thai"
  ]
 },
 {
  "code": "TJ",
  "name": "Tajikistan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": [
   "Republic of Tajikistan",
   "Toçikiston",
   "Ҷумҳурии Тоҷикистон",
   "Çumhuriyi Toçikiston"
  ]
 },
 {
  "code": "TL",
  "name": "Timor-Leste",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Democratic Republic of Timor-Leste",
   "East Timor",
   "Timor",
   "República Democrática de Timor-Leste",
   "Repúblika Demokrátika Timór-Leste",
   "Timór Lorosa'e",
   "Timor Lorosae"
  ]
 },
 {
  "code": "TM",
  "name": "Turkmenistan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": []
 },
 {
  "code": "TN",
  "name": "Tunisia",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "Tunisian Republic",
   "Republic of Tunisia",
   "al-Jumhūriyyah at-Tūnisiyyah"
  ]
 },
 {
  "code": "TO",
  "name": "Tonga",
  "region": "Oceania",
  "subregion": "Polynesia",
  "aliases": [
   "Kingdom of Tonga"
  ]
 },
 {
  "code": "TR",
  "name": "Türkiye",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Republic of Türkiye",
   "Turkiye",
   "Republic of Turkey",
   "Türkiye Cumhuriyeti"
  ]
 },
 {
  "code": "TT",
  "name": "Trinidad and Tobago",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "Republic of Trinidad and Tobago"
  ]
 },
 {
  "code": "TV",
  "name": "Tuvalu",
  "region": "Oceania",
  "subregion": "Polynesia",
  "aliases": []
 },
 {
  "code": "TZ",
  "name": "Tanzania",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "United Republic of Tanzania",
   "Tanzania, United Republic of",
   "Jamhuri ya Muungano wa Tanzania"
  ]
 },
 {
  "code": "UA",
  "name": "Ukraine",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "aliases": [
   "Ukrayina"
  ]
 },
 {
  "code": "UG",
  "name": "Uganda",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Uganda",
   "Jamhuri ya Uganda"
  ]
 },
 {
  "code": "US",
  "name": "United States",
  "region": "Americas",
  "subregion": "North America",
  "aliases": [
   "United States of America",
   "USA"
  ]
 },
 {
  "code": "UY",
  "name": "Uruguay",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Oriental Republic of Uruguay",
   "República Oriental del Uruguay"
  ]
 },
 {
  "code": "UZ",
  "name": "Uzbekistan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": [
   "Republic of Uzbekistan",
   "O‘zbekiston Respublikasi",
   "Ўзбекистон Республикаси"
  ]
 },
 {
  "code": "VA",
  "name": "Vatican City",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "Vatican City State",
   "Holy See (Vatican City State)",
   "Vatican",
   "Stato della Città del Vaticano"
  ]
 },
 {
  "code": "VC",
  "name": "Saint Vincent and the Grenadines",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": []
 },
 {
  "code": "VE",
  "name": "Venezuela",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "Bolivarian Republic of Venezuela",
   "Venezuela, Bolivarian Republic of",
   "República Bolivariana de Venezuela"
  ]
 },
 {
  "code": "VN",
  "name": "Vietnam",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "Socialist Republic of Vietnam",
   "Cộng hòa Xã hội chủ nghĩa Việt Nam",
   "Viet Nam"
  ]
 },
 {
  "code": "VU",
  "name": "Vanuatu",
  "region": "Oceania",
  "subregion": "Melanesia",
  "aliases": [
   "Republic of Vanuatu",
   "Ripablik blong Vanuatu",
   "République de Vanuatu"
  ]
 },
 {
  "code": "WS",
  "name": "Samoa",
  "region": "Oceania",
  "subregion": "Polynesia",
  "aliases": [
   "Independent State of Samoa",
   "Malo Saʻoloto Tutoʻatasi o Sāmoa"
  ]
 },
 {
  "code": "YE",
  "name": "Yemen",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "Republic of Yemen",
   "Yemeni Republic",
   "al-Jumhūriyyah al-Yamaniyyah"
  ]
 },
 {
  "code": "ZA",
  "name": "South Africa",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "Republic of South Africa",
   "RSA",
   "Suid-Afrika"
  ]
 },
 {
  "code": "ZM",
  "name": "Zambia",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Zambia"
  ]
 },
 {
  "code": "ZW",
  "name": "Zimbabwe",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "Republic of Zimbabwe"
  ]
 }
];
