// Generated by scripts/vendor-flags.mjs from mledoze/countries
// (https://github.com/mledoze/countries, ODbL 1.0). Do not edit by hand.
//
// Every seed picks flags by their place in this list, so its order is part
// of every game ever played. See the script before regenerating it.

export const COUNTRIES = [
 {
  "code": "AD",
  "name": "Andorra",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "AD",
   "Principality of Andorra",
   "Principat d'Andorra"
  ]
 },
 {
  "code": "AE",
  "name": "United Arab Emirates",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "AE",
   "UAE",
   "Emirates",
   "الإمارات",
   "الإمارات العربية المتحدة"
  ]
 },
 {
  "code": "AF",
  "name": "Afghanistan",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "AF",
   "Islamic Republic of Afghanistan",
   "Afġānistān",
   "افغانستان",
   "جمهوری اسلامی افغانستان",
   "د افغانستان اسلامي جمهوریت",
   "Owganystan",
   "Owganystan Yslam Respublikasy"
  ]
 },
 {
  "code": "AG",
  "name": "Antigua and Barbuda",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "AG"
  ]
 },
 {
  "code": "AL",
  "name": "Albania",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "AL",
   "Republic of Albania",
   "Shqipëri",
   "Shqipëria",
   "Shqipnia",
   "Republika e Shqipërisë"
  ]
 },
 {
  "code": "AM",
  "name": "Armenia",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "AM",
   "Republic of Armenia",
   "Hayastan",
   "Հայաստանի Հանրապետություն",
   "Հայաստան"
  ]
 },
 {
  "code": "AO",
  "name": "Angola",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "AO",
   "Republic of Angola",
   "República de Angola",
   "ʁɛpublika de an'ɡɔla"
  ]
 },
 {
  "code": "AR",
  "name": "Argentina",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "AR",
   "Argentine Republic",
   "República Argentina"
  ]
 },
 {
  "code": "AT",
  "name": "Austria",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "AT",
   "Republic of Austria",
   "Osterreich",
   "Oesterreich",
   "Österreich",
   "Republik Österreich"
  ]
 },
 {
  "code": "AU",
  "name": "Australia",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "aliases": [
   "AU",
   "Commonwealth of Australia"
  ]
 },
 {
  "code": "AZ",
  "name": "Azerbaijan",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "AZ",
   "Republic of Azerbaijan",
   "Azərbaycan Respublikası",
   "Azərbaycan",
   "Азербайджан",
   "Азербайджанская Республика"
  ]
 },
 {
  "code": "BA",
  "name": "Bosnia and Herzegovina",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "BA",
   "Bosnia-Herzegovina",
   "Босна и Херцеговина",
   "Bosna i Hercegovina",
   "Боснa и Херцеговина",
   "BiH",
   "Bosnia"
  ]
 },
 {
  "code": "BB",
  "name": "Barbados",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "BB"
  ]
 },
 {
  "code": "BD",
  "name": "Bangladesh",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "BD",
   "People's Republic of Bangladesh",
   "Gônôprôjatôntri Bangladesh",
   "বাংলাদেশ",
   "বাংলাদেশ গণপ্রজাতন্ত্রী"
  ]
 },
 {
  "code": "BE",
  "name": "Belgium",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "BE",
   "Kingdom of Belgium",
   "België",
   "Belgie",
   "Belgien",
   "Belgique",
   "Koninkrijk België",
   "Royaume de Belgique",
   "Königreich Belgien"
  ]
 },
 {
  "code": "BF",
  "name": "Burkina Faso",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "BF",
   "République du Burkina"
  ]
 },
 {
  "code": "BG",
  "name": "Bulgaria",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "BG",
   "Republic of Bulgaria",
   "Република България",
   "България"
  ]
 },
 {
  "code": "BH",
  "name": "Bahrain",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "BH",
   "Kingdom of Bahrain",
   "Mamlakat al-Baḥrayn",
   "البحرين",
   "مملكة البحرين"
  ]
 },
 {
  "code": "BI",
  "name": "Burundi",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "BI",
   "Republic of Burundi",
   "Republika y'Uburundi",
   "République du Burundi",
   "Uburundi",
   "Republika y'Uburundi "
  ]
 },
 {
  "code": "BJ",
  "name": "Benin",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "BJ",
   "Republic of Benin",
   "République du Bénin",
   "Bénin"
  ]
 },
 {
  "code": "BN",
  "name": "Brunei",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "BN",
   "Nation of Brunei, Abode of Peace",
   "Brunei Darussalam",
   "Nation of Brunei",
   "the Abode of Peace",
   "Negara Brunei Darussalam",
   "Nation of Brunei, Abode Damai"
  ]
 },
 {
  "code": "BO",
  "name": "Bolivia",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "BO",
   "Plurinational State of Bolivia",
   "Buliwya",
   "Wuliwya",
   "Bolivia, Plurinational State of",
   "Estado Plurinacional de Bolivia",
   "Buliwya Mamallaqta",
   "Wuliwya Suyu",
   "Tetã Volívia",
   "Volívia"
  ]
 },
 {
  "code": "BR",
  "name": "Brazil",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "BR",
   "Federative Republic of Brazil",
   "Brasil",
   "República Federativa do Brasil"
  ]
 },
 {
  "code": "BS",
  "name": "Bahamas",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "BS",
   "Commonwealth of the Bahamas"
  ]
 },
 {
  "code": "BT",
  "name": "Bhutan",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "BT",
   "Kingdom of Bhutan",
   "འབྲུག་ཡུལ་",
   "འབྲུག་རྒྱལ་ཁབ་"
  ]
 },
 {
  "code": "BW",
  "name": "Botswana",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "BW",
   "Republic of Botswana",
   "Lefatshe la Botswana"
  ]
 },
 {
  "code": "BY",
  "name": "Belarus",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "aliases": [
   "BY",
   "Republic of Belarus",
   "Bielaruś",
   "Белоруссия",
   "Республика Белоруссия",
   "Белару́сь",
   "Рэспубліка Беларусь",
   "Беларусь",
   "Республика Беларусь"
  ]
 },
 {
  "code": "BZ",
  "name": "Belize",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "BZ",
   "Belice"
  ]
 },
 {
  "code": "CA",
  "name": "Canada",
  "region": "Americas",
  "subregion": "North America",
  "aliases": [
   "CA"
  ]
 },
 {
  "code": "CD",
  "name": "DR Congo",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "CD",
   "Democratic Republic of the Congo",
   "Congo-Kinshasa",
   "Congo, the Democratic Republic of the",
   "Democratic Republic of Congo",
   "DRC",
   "RD Congo",
   "République démocratique du Congo",
   "Repubilika ya Kongo Demokratiki",
   "Republiki ya Kongó Demokratiki",
   "Ditunga dia Kongu wa Mungalaata",
   "Jamhuri ya Kidemokrasia ya Kongo",
   "Zaire"
  ]
 },
 {
  "code": "CF",
  "name": "Central African Republic",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "CF",
   "République centrafricaine",
   "Bêafrîka",
   "Ködörösêse tî Bêafrîka",
   "CAR"
  ]
 },
 {
  "code": "CG",
  "name": "Congo",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "CG",
   "Republic of the Congo",
   "Congo-Brazzaville",
   "République du Congo",
   "Repubilika ya Kongo",
   "Republíki ya Kongó"
  ]
 },
 {
  "code": "CH",
  "name": "Switzerland",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "CH",
   "Swiss Confederation",
   "Schweiz",
   "Suisse",
   "Svizzera",
   "Svizra",
   "Confédération suisse",
   "Schweizerische Eidgenossenschaft",
   "Confederazione Svizzera",
   "Confederaziun svizra"
  ]
 },
 {
  "code": "CI",
  "name": "Ivory Coast",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "CI",
   "Republic of Côte d'Ivoire",
   "Côte d'Ivoire",
   "Cote d'Ivoire",
   "République de Côte d'Ivoire"
  ]
 },
 {
  "code": "CL",
  "name": "Chile",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "CL",
   "Republic of Chile",
   "República de Chile"
  ]
 },
 {
  "code": "CM",
  "name": "Cameroon",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "CM",
   "Republic of Cameroon",
   "République du Cameroun",
   "Cameroun"
  ]
 },
 {
  "code": "CN",
  "name": "China",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": [
   "CN",
   "People's Republic of China",
   "Zhōngguó",
   "Zhongguo",
   "Zhonghua",
   "中华人民共和国",
   "Zhōnghuá Rénmín Gònghéguó",
   "中国",
   "PRC"
  ]
 },
 {
  "code": "CO",
  "name": "Colombia",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "CO",
   "Republic of Colombia",
   "República de Colombia"
  ]
 },
 {
  "code": "CR",
  "name": "Costa Rica",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "CR",
   "Republic of Costa Rica",
   "República de Costa Rica"
  ]
 },
 {
  "code": "CU",
  "name": "Cuba",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "CU",
   "Republic of Cuba",
   "República de Cuba"
  ]
 },
 {
  "code": "CV",
  "name": "Cape Verde",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "CV",
   "Republic of Cabo Verde",
   "República de Cabo Verde",
   "Cabo Verde"
  ]
 },
 {
  "code": "CY",
  "name": "Cyprus",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "CY",
   "Republic of Cyprus",
   "Kýpros",
   "Kıbrıs",
   "Κυπριακή Δημοκρατία",
   "Kıbrıs Cumhuriyeti",
   "Κύπρος",
   "Δημοκρατία της Κύπρος"
  ]
 },
 {
  "code": "CZ",
  "name": "Czechia",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "CZ",
   "Czech Republic",
   "Česká republika",
   "Česko",
   "Czech"
  ]
 },
 {
  "code": "DE",
  "name": "Germany",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "DE",
   "Federal Republic of Germany",
   "Bundesrepublik Deutschland",
   "Deutschland"
  ]
 },
 {
  "code": "DJ",
  "name": "Djibouti",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "DJ",
   "Republic of Djibouti",
   "Jabuuti",
   "Gabuuti",
   "République de Djibouti",
   "Gabuutih Ummuuno",
   "Jamhuuriyadda Jabuuti",
   "جيبوتي",
   "جمهورية جيبوتي"
  ]
 },
 {
  "code": "DK",
  "name": "Denmark",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "DK",
   "Kingdom of Denmark",
   "Danmark",
   "Kongeriget Danmark"
  ]
 },
 {
  "code": "DM",
  "name": "Dominica",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "DM",
   "Commonwealth of Dominica",
   "Dominique",
   "Wai‘tu kubuli"
  ]
 },
 {
  "code": "DO",
  "name": "Dominican Republic",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "DO",
   "República Dominicana"
  ]
 },
 {
  "code": "DZ",
  "name": "Algeria",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "DZ",
   "People's Democratic Republic of Algeria",
   "Dzayer",
   "Algérie",
   "الجزائر",
   "الجمهورية الديمقراطية الشعبية الجزائرية"
  ]
 },
 {
  "code": "EC",
  "name": "Ecuador",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "EC",
   "Republic of Ecuador",
   "República del Ecuador"
  ]
 },
 {
  "code": "EE",
  "name": "Estonia",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "EE",
   "Republic of Estonia",
   "Eesti",
   "Eesti Vabariik"
  ]
 },
 {
  "code": "EG",
  "name": "Egypt",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "EG",
   "Arab Republic of Egypt",
   "مصر",
   "جمهورية مصر العربية"
  ]
 },
 {
  "code": "ER",
  "name": "Eritrea",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "ER",
   "State of Eritrea",
   "ሃገረ ኤርትራ",
   "Dawlat Iritriyá",
   "ʾErtrā",
   "Iritriyā",
   "إريتريا",
   "دولة إريتريا",
   "ኤርትራ"
  ]
 },
 {
  "code": "ES",
  "name": "Spain",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "ES",
   "Kingdom of Spain",
   "Reino de España",
   "España"
  ]
 },
 {
  "code": "ET",
  "name": "Ethiopia",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "ET",
   "Federal Democratic Republic of Ethiopia",
   "ʾĪtyōṗṗyā",
   "የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ",
   "ኢትዮጵያ"
  ]
 },
 {
  "code": "FI",
  "name": "Finland",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "FI",
   "Republic of Finland",
   "Suomi",
   "Suomen tasavalta",
   "Republiken Finland"
  ]
 },
 {
  "code": "FJ",
  "name": "Fiji",
  "region": "Oceania",
  "subregion": "Melanesia",
  "aliases": [
   "FJ",
   "Republic of Fiji",
   "Viti",
   "Matanitu ko Viti",
   "Fijī Gaṇarājya",
   "Matanitu Tugalala o Viti",
   "फिजी",
   "रिपब्लिक ऑफ फीजी"
  ]
 },
 {
  "code": "FM",
  "name": "Micronesia",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "FM",
   "Federated States of Micronesia",
   "Micronesia, Federated States of"
  ]
 },
 {
  "code": "FR",
  "name": "France",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "FR",
   "French Republic",
   "République française"
  ]
 },
 {
  "code": "GA",
  "name": "Gabon",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "GA",
   "Gabonese Republic",
   "République Gabonaise",
   "République gabonaise"
  ]
 },
 {
  "code": "GB",
  "name": "United Kingdom",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "GB",
   "United Kingdom of Great Britain and Northern Ireland",
   "UK",
   "Great Britain",
   "Britain"
  ]
 },
 {
  "code": "GD",
  "name": "Grenada",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "GD"
  ]
 },
 {
  "code": "GE",
  "name": "Georgia",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "GE",
   "Sakartvelo",
   "საქართველო"
  ]
 },
 {
  "code": "GH",
  "name": "Ghana",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "GH",
   "Republic of Ghana"
  ]
 },
 {
  "code": "GM",
  "name": "Gambia",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "GM",
   "Republic of the Gambia"
  ]
 },
 {
  "code": "GN",
  "name": "Guinea",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "GN",
   "Republic of Guinea",
   "République de Guinée",
   "Guinée"
  ]
 },
 {
  "code": "GQ",
  "name": "Equatorial Guinea",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "GQ",
   "Republic of Equatorial Guinea",
   "República de Guinea Ecuatorial",
   "République de Guinée équatoriale",
   "República da Guiné Equatorial",
   "Guinée équatoriale",
   "République de la Guinée Équatoriale",
   "Guiné Equatorial",
   "Guinea Ecuatorial"
  ]
 },
 {
  "code": "GR",
  "name": "Greece",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "GR",
   "Hellenic Republic",
   "Elláda",
   "Ελληνική Δημοκρατία",
   "Ελλάδα"
  ]
 },
 {
  "code": "GT",
  "name": "Guatemala",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "GT",
   "Republic of Guatemala",
   "República de Guatemala"
  ]
 },
 {
  "code": "GW",
  "name": "Guinea-Bissau",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "GW",
   "Republic of Guinea-Bissau",
   "República da Guiné-Bissau",
   "Guiné-Bissau"
  ]
 },
 {
  "code": "GY",
  "name": "Guyana",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "GY",
   "Co-operative Republic of Guyana"
  ]
 },
 {
  "code": "HN",
  "name": "Honduras",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "HN",
   "Republic of Honduras",
   "República de Honduras"
  ]
 },
 {
  "code": "HR",
  "name": "Croatia",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "HR",
   "Republic of Croatia",
   "Hrvatska",
   "Republika Hrvatska"
  ]
 },
 {
  "code": "HT",
  "name": "Haiti",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "HT",
   "Republic of Haiti",
   "République d'Haïti",
   "Repiblik Ayiti",
   "Haïti",
   "Ayiti"
  ]
 },
 {
  "code": "HU",
  "name": "Hungary",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "HU",
   "Magyarország"
  ]
 },
 {
  "code": "ID",
  "name": "Indonesia",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "ID",
   "Republic of Indonesia",
   "Republik Indonesia"
  ]
 },
 {
  "code": "IE",
  "name": "Ireland",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "IE",
   "Republic of Ireland",
   "Éire",
   "Poblacht na hÉireann"
  ]
 },
 {
  "code": "IL",
  "name": "Israel",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "IL",
   "State of Israel",
   "Medīnat Yisrā'el",
   "إسرائيل",
   "دولة إسرائيل",
   "ישראל",
   "מדינת ישראל"
  ]
 },
 {
  "code": "IN",
  "name": "India",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "IN",
   "Republic of India",
   "Bhārat",
   "Bharat Ganrajya",
   "இந்தியா",
   "भारत",
   "भारत गणराज्य",
   "இந்தியக் குடியரசு"
  ]
 },
 {
  "code": "IQ",
  "name": "Iraq",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "IQ",
   "Republic of Iraq",
   "Jumhūriyyat al-‘Irāq",
   "العراق",
   "جمهورية العراق",
   "ܩܘܼܛܢܵܐ",
   "ܩܘܼܛܢܵܐ ܐܝܼܪܲܩ",
   "کۆماری",
   "کۆماری عێراق"
  ]
 },
 {
  "code": "IR",
  "name": "Iran",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "IR",
   "Islamic Republic of Iran",
   "Iran, Islamic Republic of",
   "Jomhuri-ye Eslāmi-ye Irān",
   "ایران",
   "جمهوری اسلامی ایران"
  ]
 },
 {
  "code": "IS",
  "name": "Iceland",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "IS",
   "Island",
   "Republic of Iceland",
   "Lýðveldið Ísland",
   "Ísland"
  ]
 },
 {
  "code": "IT",
  "name": "Italy",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "IT",
   "Italian Republic",
   "Repubblica italiana",
   "Italia"
  ]
 },
 {
  "code": "JM",
  "name": "Jamaica",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "JM"
  ]
 },
 {
  "code": "JO",
  "name": "Jordan",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "JO",
   "Hashemite Kingdom of Jordan",
   "al-Mamlakah al-Urdunīyah al-Hāshimīyah",
   "الأردن",
   "المملكة الأردنية الهاشمية"
  ]
 },
 {
  "code": "JP",
  "name": "Japan",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": [
   "JP",
   "Nippon",
   "Nihon",
   "日本"
  ]
 },
 {
  "code": "KE",
  "name": "Kenya",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "KE",
   "Republic of Kenya",
   "Jamhuri ya Kenya"
  ]
 },
 {
  "code": "KG",
  "name": "Kyrgyzstan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": [
   "KG",
   "Kyrgyz Republic",
   "Киргизия",
   "Кыргыз Республикасы",
   "Kyrgyz Respublikasy",
   "Кыргызстан",
   "Кыргызская Республика"
  ]
 },
 {
  "code": "KH",
  "name": "Cambodia",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "KH",
   "Kingdom of Cambodia",
   "Kâmpŭchéa",
   "ព្រះរាជាណាចក្រកម្ពុជា"
  ]
 },
 {
  "code": "KI",
  "name": "Kiribati",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "KI",
   "Independent and Sovereign Republic of Kiribati",
   "Republic of Kiribati",
   "Ribaberiki Kiribati"
  ]
 },
 {
  "code": "KM",
  "name": "Comoros",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "KM",
   "Union of the Comoros",
   "Union des Comores",
   "Udzima wa Komori",
   "al-Ittiḥād al-Qumurī",
   "جزر القمر",
   "الاتحاد القمري",
   "Comores",
   "Komori"
  ]
 },
 {
  "code": "KN",
  "name": "Saint Kitts and Nevis",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "KN",
   "Federation of Saint Christopher and Nevis",
   "St Kitts"
  ]
 },
 {
  "code": "KP",
  "name": "North Korea",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": [
   "KP",
   "Democratic People's Republic of Korea",
   "DPRK",
   "조선민주주의인민공화국",
   "Chosŏn Minjujuŭi Inmin Konghwaguk",
   "Korea, Democratic People's Republic of",
   "북한",
   "북조선",
   "조선"
  ]
 },
 {
  "code": "KR",
  "name": "South Korea",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": [
   "KR",
   "Republic of Korea",
   "Korea, Republic of",
   "남한",
   "남조선",
   "한국",
   "대한민국",
   "ROK"
  ]
 },
 {
  "code": "KW",
  "name": "Kuwait",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "KW",
   "State of Kuwait",
   "Dawlat al-Kuwait",
   "الكويت",
   "دولة الكويت"
  ]
 },
 {
  "code": "KZ",
  "name": "Kazakhstan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": [
   "KZ",
   "Republic of Kazakhstan",
   "Qazaqstan",
   "Казахстан",
   "Қазақстан Республикасы",
   "Qazaqstan Respublïkası",
   "Республика Казахстан",
   "Respublika Kazakhstan",
   "Қазақстан"
  ]
 },
 {
  "code": "LA",
  "name": "Laos",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "LA",
   "Lao People's Democratic Republic",
   "Lao",
   "Sathalanalat Paxathipatai Paxaxon Lao",
   "ສປປລາວ",
   "ສາທາລະນະ ຊາທິປະໄຕ ຄົນລາວ ຂອງ"
  ]
 },
 {
  "code": "LB",
  "name": "Lebanon",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "LB",
   "Lebanese Republic",
   "Al-Jumhūrīyah Al-Libnānīyah",
   "لبنان",
   "الجمهورية اللبنانية",
   "Liban",
   "République libanaise"
  ]
 },
 {
  "code": "LC",
  "name": "Saint Lucia",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "LC"
  ]
 },
 {
  "code": "LI",
  "name": "Liechtenstein",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "LI",
   "Principality of Liechtenstein",
   "Fürstentum Liechtenstein"
  ]
 },
 {
  "code": "LK",
  "name": "Sri Lanka",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "LK",
   "Democratic Socialist Republic of Sri Lanka",
   "ilaṅkai",
   "ශ්‍රී ලංකාව",
   "ශ්‍රී ලංකා ප්‍රජාතාන්ත්‍රික සමාජවාදී ජනරජය",
   "இலங்கை",
   "இலங்கை சனநாயக சோசலிசக் குடியரசு"
  ]
 },
 {
  "code": "LR",
  "name": "Liberia",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "LR",
   "Republic of Liberia"
  ]
 },
 {
  "code": "LS",
  "name": "Lesotho",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "LS",
   "Kingdom of Lesotho",
   "Muso oa Lesotho"
  ]
 },
 {
  "code": "LT",
  "name": "Lithuania",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "LT",
   "Republic of Lithuania",
   "Lietuvos Respublika",
   "Lietuva",
   "Lietuvos Respublikos"
  ]
 },
 {
  "code": "LU",
  "name": "Luxembourg",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "LU",
   "Grand Duchy of Luxembourg",
   "Grand-Duché de Luxembourg",
   "Großherzogtum Luxemburg",
   "Groussherzogtum Lëtzebuerg",
   "Luxemburg",
   "Lëtzebuerg"
  ]
 },
 {
  "code": "LV",
  "name": "Latvia",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "LV",
   "Republic of Latvia",
   "Latvijas Republika",
   "Latvija",
   "Latvijas Republikas"
  ]
 },
 {
  "code": "LY",
  "name": "Libya",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "LY",
   "State of Libya",
   "Dawlat Libya",
   "ليبيا",
   "دولة ليبيا"
  ]
 },
 {
  "code": "MA",
  "name": "Morocco",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "MA",
   "Kingdom of Morocco",
   "Al-Mamlakah al-Maġribiyah",
   "المغرب",
   "المملكة المغربية",
   "ⵍⵎⴰⵖⵔⵉⴱ",
   "ⵜⴰⴳⵍⴷⵉⵜ ⵏ ⵍⵎⵖⵔⵉⴱ"
  ]
 },
 {
  "code": "MC",
  "name": "Monaco",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "MC",
   "Principality of Monaco",
   "Principauté de Monaco"
  ]
 },
 {
  "code": "MD",
  "name": "Moldova",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "aliases": [
   "MD",
   "Republic of Moldova",
   "Moldova, Republic of",
   "Republica Moldova"
  ]
 },
 {
  "code": "ME",
  "name": "Montenegro",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "ME",
   "Crna Gora",
   "Црна Гора"
  ]
 },
 {
  "code": "MG",
  "name": "Madagascar",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "MG",
   "Republic of Madagascar",
   "Repoblikan'i Madagasikara",
   "République de Madagascar",
   "Madagasikara"
  ]
 },
 {
  "code": "MH",
  "name": "Marshall Islands",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "MH",
   "Republic of the Marshall Islands",
   "Aolepān Aorōkin M̧ajeļ",
   "M̧ajeļ"
  ]
 },
 {
  "code": "MK",
  "name": "North Macedonia",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "MK",
   "Republic of North Macedonia",
   "The former Yugoslav Republic of Macedonia",
   "Macedonia, The Former Yugoslav Republic of",
   "Република Северна Македонија",
   "Macedonia",
   "Македонија"
  ]
 },
 {
  "code": "ML",
  "name": "Mali",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "ML",
   "Republic of Mali",
   "République du Mali"
  ]
 },
 {
  "code": "MM",
  "name": "Myanmar",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "MM",
   "Republic of the Union of Myanmar",
   "Burma",
   "Pyidaunzu Thanmăda Myăma Nainngandaw",
   "မြန်မာ",
   "ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံတော်"
  ]
 },
 {
  "code": "MN",
  "name": "Mongolia",
  "region": "Asia",
  "subregion": "Eastern Asia",
  "aliases": [
   "MN",
   "Монгол улс"
  ]
 },
 {
  "code": "MR",
  "name": "Mauritania",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "MR",
   "Islamic Republic of Mauritania",
   "al-Jumhūriyyah al-ʾIslāmiyyah al-Mūrītāniyyah",
   "موريتانيا",
   "الجمهورية الإسلامية الموريتانية"
  ]
 },
 {
  "code": "MT",
  "name": "Malta",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "MT",
   "Republic of Malta",
   "Repubblika ta' Malta",
   "Repubblika ta ' Malta"
  ]
 },
 {
  "code": "MU",
  "name": "Mauritius",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "MU",
   "Republic of Mauritius",
   "République de Maurice",
   "Maurice",
   "Moris",
   "Republik Moris"
  ]
 },
 {
  "code": "MV",
  "name": "Maldives",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "MV",
   "Republic of the Maldives",
   "Maldive Islands",
   "Dhivehi Raajjeyge Jumhooriyya",
   "ދިވެހިރާއްޖޭގެ",
   "ދިވެހިރާއްޖޭގެ ޖުމްހޫރިއްޔާ"
  ]
 },
 {
  "code": "MW",
  "name": "Malawi",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "MW",
   "Republic of Malawi",
   "Malaŵi",
   "Chalo cha Malawi, Dziko la Malaŵi"
  ]
 },
 {
  "code": "MX",
  "name": "Mexico",
  "region": "Americas",
  "subregion": "North America",
  "aliases": [
   "MX",
   "United Mexican States",
   "Mexicanos",
   "Estados Unidos Mexicanos",
   "México"
  ]
 },
 {
  "code": "MY",
  "name": "Malaysia",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "MY",
   "مليسيا"
  ]
 },
 {
  "code": "MZ",
  "name": "Mozambique",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "MZ",
   "Republic of Mozambique",
   "República de Moçambique",
   "Moçambique"
  ]
 },
 {
  "code": "NA",
  "name": "Namibia",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "NA",
   "Republic of Namibia",
   "Namibië",
   "Republiek van Namibië",
   "Republik Namibia",
   "Lefatshe la Namibia"
  ]
 },
 {
  "code": "NE",
  "name": "Niger",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "NE",
   "Republic of Niger",
   "Nijar",
   "République du Niger"
  ]
 },
 {
  "code": "NG",
  "name": "Nigeria",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "NG",
   "Federal Republic of Nigeria",
   "Nijeriya",
   "Naíjíríà"
  ]
 },
 {
  "code": "NI",
  "name": "Nicaragua",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "NI",
   "Republic of Nicaragua",
   "República de Nicaragua"
  ]
 },
 {
  "code": "NL",
  "name": "Netherlands",
  "region": "Europe",
  "subregion": "Western Europe",
  "aliases": [
   "NL",
   "Kingdom of the Netherlands",
   "Holland",
   "Nederland",
   "The Netherlands",
   "Koninkrijk der Nederlanden"
  ]
 },
 {
  "code": "NO",
  "name": "Norway",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "NO",
   "Kingdom of Norway",
   "Norge",
   "Noreg",
   "Kongeriket Norge",
   "Kongeriket Noreg",
   "Norgga",
   "Norgga gonagasriika"
  ]
 },
 {
  "code": "NP",
  "name": "Nepal",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "NP",
   "Federal Democratic Republic of Nepal",
   "Loktāntrik Ganatantra Nepāl",
   "नेपाल",
   "नेपाल संघीय लोकतान्त्रिक गणतन्त्र"
  ]
 },
 {
  "code": "NR",
  "name": "Nauru",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "NR",
   "Republic of Nauru",
   "Naoero",
   "Pleasant Island",
   "Ripublik Naoero"
  ]
 },
 {
  "code": "NZ",
  "name": "New Zealand",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "aliases": [
   "NZ",
   "Aotearoa"
  ]
 },
 {
  "code": "OM",
  "name": "Oman",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "OM",
   "Sultanate of Oman",
   "Salṭanat ʻUmān",
   "عمان",
   "سلطنة عمان"
  ]
 },
 {
  "code": "PA",
  "name": "Panama",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "PA",
   "Republic of Panama",
   "República de Panamá",
   "Panamá"
  ]
 },
 {
  "code": "PE",
  "name": "Peru",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "PE",
   "Republic of Peru",
   "República del Perú",
   "Piruw",
   "Piruw Suyu",
   "Piruw Ripuwlika",
   "Perú"
  ]
 },
 {
  "code": "PG",
  "name": "Papua New Guinea",
  "region": "Oceania",
  "subregion": "Melanesia",
  "aliases": [
   "PG",
   "Independent State of Papua New Guinea",
   "Independen Stet bilong Papua Niugini",
   "Papua Niu Gini",
   "Papua Niugini",
   "PNG"
  ]
 },
 {
  "code": "PH",
  "name": "Philippines",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "PH",
   "Republic of the Philippines",
   "Repúblika ng Pilipinas",
   "Pilipinas",
   "Republika ng Pilipinas"
  ]
 },
 {
  "code": "PK",
  "name": "Pakistan",
  "region": "Asia",
  "subregion": "Southern Asia",
  "aliases": [
   "PK",
   "Islamic Republic of Pakistan",
   "Pākistān",
   "Islāmī Jumhūriya'eh Pākistān",
   "پاكستان",
   "اسلامی جمہوریۂ پاكستان"
  ]
 },
 {
  "code": "PL",
  "name": "Poland",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "PL",
   "Republic of Poland",
   "Rzeczpospolita Polska",
   "Polska"
  ]
 },
 {
  "code": "PT",
  "name": "Portugal",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "PT",
   "Portuguese Republic",
   "Portuguesa",
   "República Portuguesa",
   "República português"
  ]
 },
 {
  "code": "PW",
  "name": "Palau",
  "region": "Oceania",
  "subregion": "Micronesia",
  "aliases": [
   "PW",
   "Republic of Palau",
   "Beluu er a Belau",
   "Belau"
  ]
 },
 {
  "code": "PY",
  "name": "Paraguay",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "PY",
   "Republic of Paraguay",
   "República del Paraguay",
   "Tetã Paraguái",
   "Paraguái",
   "República de Paraguay"
  ]
 },
 {
  "code": "QA",
  "name": "Qatar",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "QA",
   "State of Qatar",
   "Dawlat Qaṭar",
   "قطر",
   "دولة قطر"
  ]
 },
 {
  "code": "RO",
  "name": "Romania",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "RO",
   "Rumania",
   "Roumania",
   "România"
  ]
 },
 {
  "code": "RS",
  "name": "Serbia",
  "region": "Europe",
  "subregion": "Southeast Europe",
  "aliases": [
   "RS",
   "Republic of Serbia",
   "Srbija",
   "Republika Srbija",
   "Србија",
   "Република Србија"
  ]
 },
 {
  "code": "RU",
  "name": "Russia",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "aliases": [
   "RU",
   "Russian Federation",
   "Российская Федерация",
   "Россия"
  ]
 },
 {
  "code": "RW",
  "name": "Rwanda",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "RW",
   "Republic of Rwanda",
   "Repubulika y'u Rwanda",
   "République du Rwanda",
   "République rwandaise"
  ]
 },
 {
  "code": "SA",
  "name": "Saudi Arabia",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "SA",
   "Kingdom of Saudi Arabia",
   "Saudi",
   "Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah",
   "السعودية",
   "المملكة العربية السعودية",
   "KSA"
  ]
 },
 {
  "code": "SB",
  "name": "Solomon Islands",
  "region": "Oceania",
  "subregion": "Melanesia",
  "aliases": [
   "SB"
  ]
 },
 {
  "code": "SC",
  "name": "Seychelles",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "SC",
   "Republic of Seychelles",
   "Repiblik Sesel",
   "République des Seychelles",
   "Sesel"
  ]
 },
 {
  "code": "SD",
  "name": "Sudan",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "SD",
   "Republic of the Sudan",
   "Jumhūrīyat as-Sūdān",
   "السودان",
   "جمهورية السودان"
  ]
 },
 {
  "code": "SE",
  "name": "Sweden",
  "region": "Europe",
  "subregion": "Northern Europe",
  "aliases": [
   "SE",
   "Kingdom of Sweden",
   "Konungariket Sverige",
   "Sverige"
  ]
 },
 {
  "code": "SG",
  "name": "Singapore",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "SG",
   "Republic of Singapore",
   "Singapura",
   "Republik Singapura",
   "新加坡共和国",
   "சிங்கப்பூர்",
   "சிங்கப்பூர் குடியரசு",
   "新加坡"
  ]
 },
 {
  "code": "SI",
  "name": "Slovenia",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "SI",
   "Republic of Slovenia",
   "Republika Slovenija",
   "Slovenija"
  ]
 },
 {
  "code": "SK",
  "name": "Slovakia",
  "region": "Europe",
  "subregion": "Central Europe",
  "aliases": [
   "SK",
   "Slovak Republic",
   "Slovenská republika",
   "Slovensko"
  ]
 },
 {
  "code": "SL",
  "name": "Sierra Leone",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "SL",
   "Republic of Sierra Leone"
  ]
 },
 {
  "code": "SM",
  "name": "San Marino",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "SM",
   "Most Serene Republic of San Marino",
   "Republic of San Marino",
   "Repubblica di San Marino",
   "Serenissima Repubblica di San Marino"
  ]
 },
 {
  "code": "SN",
  "name": "Senegal",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "SN",
   "Republic of Senegal",
   "République du Sénégal",
   "Sénégal"
  ]
 },
 {
  "code": "SO",
  "name": "Somalia",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "SO",
   "Federal Republic of Somalia",
   "aṣ-Ṣūmāl",
   "Jamhuuriyadda Federaalka Soomaaliya",
   "Jumhūriyyat aṣ-Ṣūmāl al-Fiderāliyya",
   "الصومال",
   "جمهورية الصومال الفيدرالية",
   "Soomaaliya"
  ]
 },
 {
  "code": "SR",
  "name": "Suriname",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "SR",
   "Republic of Suriname",
   "Sarnam",
   "Sranangron",
   "Republiek Suriname"
  ]
 },
 {
  "code": "SS",
  "name": "South Sudan",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "SS",
   "Republic of South Sudan"
  ]
 },
 {
  "code": "ST",
  "name": "São Tomé and Príncipe",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "ST",
   "Democratic Republic of São Tomé and Príncipe",
   "Sao Tome and Principe",
   "República Democrática de São Tomé e Príncipe",
   "São Tomé e Príncipe",
   "República Democrática do São Tomé e Príncipe",
   "STP",
   "Sao Tome"
  ]
 },
 {
  "code": "SV",
  "name": "El Salvador",
  "region": "Americas",
  "subregion": "Central America",
  "aliases": [
   "SV",
   "Republic of El Salvador",
   "República de El Salvador"
  ]
 },
 {
  "code": "SY",
  "name": "Syria",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "SY",
   "Syrian Arab Republic",
   "Al-Jumhūrīyah Al-ʻArabīyah As-Sūrīyah",
   "سوريا",
   "الجمهورية العربية السورية"
  ]
 },
 {
  "code": "SZ",
  "name": "Eswatini",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "SZ",
   "Kingdom of Eswatini",
   "Swaziland",
   "weSwatini",
   "Swatini",
   "Ngwane",
   "Umbuso weSwatini",
   "eSwatini"
  ]
 },
 {
  "code": "TD",
  "name": "Chad",
  "region": "Africa",
  "subregion": "Middle Africa",
  "aliases": [
   "TD",
   "Republic of Chad",
   "Tchad",
   "République du Tchad",
   "تشاد",
   "جمهورية تشاد"
  ]
 },
 {
  "code": "TG",
  "name": "Togo",
  "region": "Africa",
  "subregion": "Western Africa",
  "aliases": [
   "TG",
   "Togolese Republic",
   "Togolese",
   "République Togolaise",
   "République togolaise"
  ]
 },
 {
  "code": "TH",
  "name": "Thailand",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "TH",
   "Kingdom of Thailand",
   "Prathet",
   "Thai",
   "ราชอาณาจักรไทย",
   "Ratcha Anachak Thai",
   "ประเทศไทย"
  ]
 },
 {
  "code": "TJ",
  "name": "Tajikistan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": [
   "TJ",
   "Republic of Tajikistan",
   "Toçikiston",
   "Ҷумҳурии Тоҷикистон",
   "Çumhuriyi Toçikiston",
   "Таджикистан",
   "Республика Таджикистан",
   "Тоҷикистон"
  ]
 },
 {
  "code": "TL",
  "name": "Timor-Leste",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "TL",
   "Democratic Republic of Timor-Leste",
   "East Timor",
   "Timor",
   "República Democrática de Timor-Leste",
   "Repúblika Demokrátika Timór-Leste",
   "Timór Lorosa'e",
   "Timor Lorosae",
   "Timór-Leste"
  ]
 },
 {
  "code": "TM",
  "name": "Turkmenistan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": [
   "TM",
   "Туркмения",
   "Туркменистан",
   "Türkmenistan"
  ]
 },
 {
  "code": "TN",
  "name": "Tunisia",
  "region": "Africa",
  "subregion": "Northern Africa",
  "aliases": [
   "TN",
   "Tunisian Republic",
   "Republic of Tunisia",
   "al-Jumhūriyyah at-Tūnisiyyah",
   "تونس",
   "الجمهورية التونسية"
  ]
 },
 {
  "code": "TO",
  "name": "Tonga",
  "region": "Oceania",
  "subregion": "Polynesia",
  "aliases": [
   "TO",
   "Kingdom of Tonga"
  ]
 },
 {
  "code": "TR",
  "name": "Türkiye",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "TR",
   "Republic of Türkiye",
   "Turkiye",
   "Republic of Turkey",
   "Türkiye Cumhuriyeti",
   "Turkey"
  ]
 },
 {
  "code": "TT",
  "name": "Trinidad and Tobago",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "TT",
   "Republic of Trinidad and Tobago"
  ]
 },
 {
  "code": "TV",
  "name": "Tuvalu",
  "region": "Oceania",
  "subregion": "Polynesia",
  "aliases": [
   "TV"
  ]
 },
 {
  "code": "TZ",
  "name": "Tanzania",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "TZ",
   "United Republic of Tanzania",
   "Tanzania, United Republic of",
   "Jamhuri ya Muungano wa Tanzania"
  ]
 },
 {
  "code": "UA",
  "name": "Ukraine",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "aliases": [
   "UA",
   "Ukrayina",
   "Україна"
  ]
 },
 {
  "code": "UG",
  "name": "Uganda",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "UG",
   "Republic of Uganda",
   "Jamhuri ya Uganda"
  ]
 },
 {
  "code": "US",
  "name": "United States",
  "region": "Americas",
  "subregion": "North America",
  "aliases": [
   "US",
   "United States of America",
   "USA",
   "America"
  ]
 },
 {
  "code": "UY",
  "name": "Uruguay",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "UY",
   "Oriental Republic of Uruguay",
   "República Oriental del Uruguay"
  ]
 },
 {
  "code": "UZ",
  "name": "Uzbekistan",
  "region": "Asia",
  "subregion": "Central Asia",
  "aliases": [
   "UZ",
   "Republic of Uzbekistan",
   "O‘zbekiston Respublikasi",
   "Ўзбекистон Республикаси",
   "Узбекистан",
   "Республика Узбекистан",
   "O‘zbekiston",
   "O'zbekiston Respublikasi"
  ]
 },
 {
  "code": "VA",
  "name": "Vatican City",
  "region": "Europe",
  "subregion": "Southern Europe",
  "aliases": [
   "VA",
   "Vatican City State",
   "Holy See (Vatican City State)",
   "Vatican",
   "Stato della Città del Vaticano",
   "Vaticano",
   "Vaticanæ",
   "Status Civitatis Vaticanæ",
   "Holy See"
  ]
 },
 {
  "code": "VC",
  "name": "Saint Vincent and the Grenadines",
  "region": "Americas",
  "subregion": "Caribbean",
  "aliases": [
   "VC",
   "SVG",
   "St Vincent"
  ]
 },
 {
  "code": "VE",
  "name": "Venezuela",
  "region": "Americas",
  "subregion": "South America",
  "aliases": [
   "VE",
   "Bolivarian Republic of Venezuela",
   "Venezuela, Bolivarian Republic of",
   "República Bolivariana de Venezuela"
  ]
 },
 {
  "code": "VN",
  "name": "Vietnam",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "aliases": [
   "VN",
   "Socialist Republic of Vietnam",
   "Cộng hòa Xã hội chủ nghĩa Việt Nam",
   "Viet Nam",
   "Việt Nam",
   "Cộng hòa xã hội chủ nghĩa Việt Nam"
  ]
 },
 {
  "code": "VU",
  "name": "Vanuatu",
  "region": "Oceania",
  "subregion": "Melanesia",
  "aliases": [
   "VU",
   "Republic of Vanuatu",
   "Ripablik blong Vanuatu",
   "République de Vanuatu"
  ]
 },
 {
  "code": "WS",
  "name": "Samoa",
  "region": "Oceania",
  "subregion": "Polynesia",
  "aliases": [
   "WS",
   "Independent State of Samoa",
   "Malo Saʻoloto Tutoʻatasi o Sāmoa",
   "Sāmoa"
  ]
 },
 {
  "code": "YE",
  "name": "Yemen",
  "region": "Asia",
  "subregion": "Western Asia",
  "aliases": [
   "YE",
   "Republic of Yemen",
   "Yemeni Republic",
   "al-Jumhūriyyah al-Yamaniyyah",
   "اليمن",
   "الجمهورية اليمنية"
  ]
 },
 {
  "code": "ZA",
  "name": "South Africa",
  "region": "Africa",
  "subregion": "Southern Africa",
  "aliases": [
   "ZA",
   "Republic of South Africa",
   "RSA",
   "Suid-Afrika",
   "Republiek van Suid-Afrika",
   "Sewula Afrika",
   "IRiphabliki yeSewula Afrika",
   "Afrika-Borwa",
   "Rephaboliki ya Afrika-Borwa ",
   "Afrika Borwa",
   "Rephaboliki ya Afrika Borwa",
   "Ningizimu Afrika",
   "IRiphabhulikhi yeNingizimu Afrika",
   "Aforika Borwa",
   "Rephaboliki ya Aforika Borwa",
   "Afrika Dzonga",
   "Riphabliki ra Afrika Dzonga",
   "Afurika Tshipembe",
   "Riphabuḽiki ya Afurika Tshipembe",
   "Mzantsi Afrika",
   "IRiphabliki yaseMzantsi Afrika",
   "IRiphabliki yaseNingizimu Afrika"
  ]
 },
 {
  "code": "ZM",
  "name": "Zambia",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "ZM",
   "Republic of Zambia"
  ]
 },
 {
  "code": "ZW",
  "name": "Zimbabwe",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "aliases": [
   "ZW",
   "Republic of Zimbabwe"
  ]
 }
];
