#!/usr/bin/env node
// Vendors the game's data, so the site never asks a third party for it at
// play time and works offline:
//
//   main-site/js/countries.js   every UN member or independent state, from
//                               mledoze/countries (ODbL), with the names a
//                               typed answer may use
//   main-site/flags/<cc>.svg    each one's flag, from flagcdn.com
//
// The original game fetched both live from restcountries.com, whose v3.1
// API has since been retired, which is what broke it.
//
// Run from the repo root, with Node 20 or later and nothing to install:
//   node scripts/vendor-flags.mjs
//
// The order of COUNTRIES is part of every seed: a seed picks flags by their
// place in this list. Re-running this after the upstream list changes moves
// old seeds onto different games, and games played on the old list stop
// verifying. Bump VERSION in main-site/sw.js afterwards, and FLAGS_VERSION
// too if any flag changed.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "main-site");
const SOURCE = "https://raw.githubusercontent.com/mledoze/countries/master/countries.json";
const FLAG = (code) => `https://flagcdn.com/${code}.svg`;
const REGIONS = ["Africa", "Americas", "Asia", "Europe", "Oceania"];

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`countries: ${res.status}`);
const raw = await res.json();

// The same rule the original game used: UN members or independent states.
const countries = raw
  .filter((c) => c.unMember === true || c.independent === true)
  .map((c) => {
    const name = c.name.common;
    const code = c.cca2;
    if (!REGIONS.includes(c.region)) throw new Error(`${code}: unknown region ${c.region}`);
    // Other names a typed answer may use: the official name and the common
    // alternatives, but not the two letter code, which would make Expert
    // a matter of knowing ISO codes.
    const aliases = [...new Set([c.name.official, ...(c.altSpellings ?? [])])].filter(
      (a) => typeof a === "string" && a !== name && a.toUpperCase() !== code && a.length <= 60
    );
    return { code, name, region: c.region, subregion: c.subregion || c.region, aliases };
  })
  .sort((a, b) => (a.code < b.code ? -1 : 1));

const header = `// Generated by scripts/vendor-flags.mjs from mledoze/countries
// (https://github.com/mledoze/countries, ODbL 1.0). Do not edit by hand.
//
// Every seed picks flags by their place in this list, so its order is part
// of every game ever played. See the script before regenerating it.

export const COUNTRIES = `;
writeFileSync(join(ROOT, "js", "countries.js"), `${header}${JSON.stringify(countries, null, 1)};\n`);
console.log(`countries.js: ${countries.length} countries`);

mkdirSync(join(ROOT, "flags"), { recursive: true });
let bytes = 0;
for (let i = 0; i < countries.length; i += 12) {
  await Promise.all(
    countries.slice(i, i + 12).map(async ({ code }) => {
      const file = code.toLowerCase();
      const r = await fetch(FLAG(file));
      if (!r.ok) throw new Error(`flag ${file}: ${r.status}`);
      const svg = await r.text();
      if (!svg.includes("<svg")) throw new Error(`flag ${file}: not an SVG`);
      bytes += svg.length;
      writeFileSync(join(ROOT, "flags", `${file}.svg`), svg);
    })
  );
}
console.log(`flags/: ${countries.length} files, ${(bytes / 1024 / 1024).toFixed(1)} MB before compression`);
console.log(`FLAG_CODES for sw.js:\n${countries.map((c) => c.code.toLowerCase()).join(" ")}`);
