#!/usr/bin/env node
// Vendors the game's data, so the site never asks a third party for it at
// play time and works offline:
//
//   main-site/js/countries.js   every UN member or independent state, from
//                               mledoze/countries (ODbL), with the names a
//                               typed answer may use
//   main-site/flags/<cc>.svg    each one's flag, from flagcdn.com
//
// The original game fetched both live from restcountries.com, whose v3.1
// API has since been retired, which is what broke it.
//
// Run from the repo root, with Node 20 or later and nothing to install:
//   node scripts/vendor-flags.mjs
//
// The order of COUNTRIES is part of every seed: a seed picks flags by their
// place in this list. Re-running this after the upstream list changes moves
// old seeds onto different games, and games played on the old list stop
// verifying. Bump VERSION in main-site/sw.js afterwards, and FLAGS_VERSION
// too if any flag changed.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "main-site");
const SOURCE = "https://raw.githubusercontent.com/mledoze/countries/master/countries.json";
const FLAG = (code) => `https://flagcdn.com/${code}.svg`;
const REGIONS = ["Africa", "Americas", "Asia", "Europe", "Oceania"];

// Names people type that the upstream list lacks: abbreviations, short and
// older forms, and names in the country's own language. Added on top of
// upstream's, by country code. Each must name only its own country;
// scripts/test-quiz.mjs checks they all match.
const EXTRA_NAMES = {
  AE: ["Emirates"],
  BA: ["BiH", "Bosnia"],
  CD: ["Congo-Kinshasa", "Zaire"],
  CF: ["CAR"],
  CG: ["Congo-Brazzaville"],
  CN: ["PRC"],
  CZ: ["Czech"],
  ES: ["España"],
  GB: ["Britain", "Great Britain"],
  KN: ["St Kitts"],
  KR: ["ROK"],
  MK: ["Macedonia"],
  NZ: ["Aotearoa"],
  PG: ["PNG"],
  SA: ["KSA"],
  ST: ["STP", "Sao Tome"],
  TR: ["Turkey"],
  US: ["America"],
  VA: ["Holy See", "Vatican"],
  VC: ["SVG", "St Vincent"],
};

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`countries: ${res.status}`);
const raw = await res.json();

// The same rule the original game used: UN members or independent states.
for (const code of Object.keys(EXTRA_NAMES)) {
  if (!raw.some((c) => c.cca2 === code)) throw new Error(`EXTRA_NAMES: no country ${code}`);
}

const countries = raw
  .filter((c) => c.unMember === true || c.independent === true)
  .map((c) => {
    const name = c.name.common;
    const code = c.cca2;
    if (!REGIONS.includes(c.region)) throw new Error(`${code}: unknown region ${c.region}`);
    // Other names a typed answer may use: the two letter code, the official
    // name, the common alternatives, the names in each official language
    // ("日本", "Deutschland"), and EXTRA_NAMES.
    const native = Object.values(c.name.native ?? {}).flatMap((n) => [n.common, n.official]);
    const aliases = [...new Set([code, c.name.official, ...(c.altSpellings ?? []), ...native, ...(EXTRA_NAMES[code] ?? [])])].filter(
      (a) => typeof a === "string" && a !== name && a.length <= 60
    );
    return { code, name, region: c.region, subregion: c.subregion || c.region, aliases };
  })
  .sort((a, b) => (a.code < b.code ? -1 : 1));

const header = `// Generated by scripts/vendor-flags.mjs from mledoze/countries
// (https://github.com/mledoze/countries, ODbL 1.0). Do not edit by hand.
//
// Every seed picks flags by their place in this list, so its order is part
// of every game ever played. See the script before regenerating it.

export const COUNTRIES = `;
writeFileSync(join(ROOT, "js", "countries.js"), `${header}${JSON.stringify(countries, null, 1)};\n`);
console.log(`countries.js: ${countries.length} countries`);

mkdirSync(join(ROOT, "flags"), { recursive: true });
let bytes = 0;
for (let i = 0; i < countries.length; i += 12) {
  await Promise.all(
    countries.slice(i, i + 12).map(async ({ code }) => {
      const file = code.toLowerCase();
      const r = await fetch(FLAG(file));
      if (!r.ok) throw new Error(`flag ${file}: ${r.status}`);
      const svg = await r.text();
      if (!svg.includes("<svg")) throw new Error(`flag ${file}: not an SVG`);
      bytes += svg.length;
      writeFileSync(join(ROOT, "flags", `${file}.svg`), svg);
    })
  );
}
console.log(`flags/: ${countries.length} files, ${(bytes / 1024 / 1024).toFixed(1)} MB before compression`);
console.log(`FLAG_CODES for sw.js:\n${countries.map((c) => c.code.toLowerCase()).join(" ")}`);
