#!/usr/bin/env node
// Measures how much of each flag is each colour, for Expert's pie charts:
//
//   main-site/js/colors.js   every country's flag colours and their shares
//
// Measured from the game's own main-site/flags/*.svg, so a pie always
// agrees with the flag shown once the answer is in. Rerun it after
// scripts/vendor-flags.mjs has changed a flag.
//
// Run from the repo root, with Node 20 or later. The SVGs are drawn with
// resvg, which is only needed here and is never part of the site:
//   npm install --no-save --no-package-lock @resvg/resvg-js
//   node scripts/vendor-colors.mjs
//
// Bump VERSION in main-site/sw.js afterwards.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

let Resvg;
try {
  ({ Resvg } = await import("@resvg/resvg-js"));
} catch {
  console.error("Needs resvg: npm install --no-save --no-package-lock @resvg/resvg-js");
  process.exit(1);
}

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "main-site");
const { COUNTRIES } = await import(pathToFileURL(join(ROOT, "js", "countries.js")).href);

// Drawn this wide, the soft edges between colours are a small part of the
// flag, and the next two rules fold them away.
const WIDTH = 600;
// A colour on less of the flag than this is folded into its nearest
// neighbour: edge blends, and the fine detail of a coat of arms.
const MIN_SHARE = 0.01;
// Colours nearer than this (RGB distance, out of 441) are one colour drawn
// two ways, such as a gradient's ends.
const SAME = 32;

const distance = (a, b) => Math.hypot((a >> 16) - (b >> 16), ((a >> 8) & 255) - ((b >> 8) & 255), (a & 255) - (b & 255));
const hex = (rgb) => `#${rgb.toString(16).padStart(6, "0").toUpperCase()}`;

function measure(svg) {
  const image = new Resvg(svg, { fitTo: { mode: "width", value: WIDTH } }).render();
  const px = image.pixels;
  const counts = new Map();
  let total = 0;
  for (let i = 0; i < px.length; i += 4) {
    // A flag that is not a rectangle (Nepal) has a clear surround.
    if (px[i + 3] < 128) continue;
    const rgb = (px[i] << 16) | (px[i + 1] << 8) | px[i + 2];
    counts.set(rgb, (counts.get(rgb) ?? 0) + 1);
    total++;
  }

  const sorted = [...counts].sort((a, b) => b[1] - a[1]);
  const kept = [];
  const rest = [];
  for (const [rgb, n] of sorted) {
    const near = kept.find((k) => distance(k.rgb, rgb) < SAME);
    if (near) near.n += n;
    else if (n / total >= MIN_SHARE) kept.push({ rgb, n });
    else rest.push([rgb, n]);
  }
  for (const [rgb, n] of rest) {
    let best = kept[0];
    for (const k of kept) if (distance(k.rgb, rgb) < distance(best.rgb, rgb)) best = k;
    best.n += n;
  }

  // Percentages to one decimal that add up to 100, the largest first.
  kept.sort((a, b) => b.n - a.n);
  const shares = kept.map((k) => Math.round((1000 * k.n) / total) / 10);
  shares[0] = Math.round((100 - shares.slice(1).reduce((a, b) => a + b, 0)) * 10) / 10;
  return kept.map((k, i) => [hex(k.rgb), shares[i]]);
}

const colors = {};
for (const { code } of COUNTRIES) {
  colors[code] = measure(readFileSync(join(ROOT, "flags", `${code.toLowerCase()}.svg`)));
}

const header = `// Generated by scripts/vendor-colors.mjs from main-site/flags/. Do not
// edit by hand.
//
// Each country's flag colours, largest first, with the percentage of the
// flag each covers: { code: [[hex, percent], ...] }.

export const FLAG_COLORS = `;
const body = Object.entries(colors)
  .map(([code, list]) => `  ${code}: ${JSON.stringify(list)},`)
  .join("\n");
writeFileSync(join(ROOT, "js", "colors.js"), `${header}{\n${body}\n};\n`);
const sizes = Object.values(colors).map((c) => c.length);
console.log(`colors.js: ${sizes.length} flags, ${Math.min(...sizes)} to ${Math.max(...sizes)} colours each`);
